# Generated by Django 3.0 on 2020-03-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='img',
            new_name='image',
        ),
    ]
