# Generated by Django 3.0 on 2020-03-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading',
            name='title',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
